### ISSUE TITLE
removing terrain glitches instances that are on top of it

### ISSUE THREAD

**Issue by DeepCanionStudio** [Zylann/godot_voxel#670]
this video shows what happens

https://github.com/Zylann/godot_voxel/assets/132934035/fc917d3d-9cb0-4774-a795-bed8fa4c3956

i'm using a voxel instancer on a voxel lod terrain
this happens on both persistent and not persistent instances
this only happens on multi mesh instances, if i delete the terrain under a scene instance nothing happens and the instance stays there

**Comment by MGilleronFJ** [comment]
I have never seen that before. I wonder if it's a new Godot bug or something? I can't think of a reason why that could be happening 🤔

**Comment by DeepCanionStudio** [comment]
i've spent 40 minutes trying to reproduce the issue on another project with the same godot version and i can't 
i also want to mention that i often get this error message in the log:

>   modules\voxel\terrain\instancing\voxel_instancer.cpp:657 - Condition "_parent == nullptr" is true.

i'm on windows, godot version is 4.2.2, my graphics card is an rx 6650xt

**Comment by DeepCanionStudio** [comment]
this is the full error

> E 0:00:00:0928   zylann::voxel::VoxelInstancer::regenerate_layer: Condition "_parent == nullptr" is true.
>   <Sorgente C++> modules\voxel\terrain\instancing\voxel_instancer.cpp:657 @ zylann::voxel::VoxelInstancer::regenerate_layer()

**Comment by MGilleronFJ** [comment]
> i've spent 40 minutes trying to reproduce the issue on another project with the same godot version and i can't

If you can't, there is very little chance that I can help fixing this by making my own repro as well... (especially if that's a Godot bug, because that's needed for Godot devs to fix it)

> modules\voxel\terrain\instancing\voxel_instancer.cpp:657 - Condition "_parent == nullptr" is true.

This error happens here: https://github.com/Zylann/godot_voxel/blob/ec063a684a4b17878d4018c015c55e2d625f724c/terrain/instancing/voxel_instancer.cpp#L657
It happens if you are trying to modify the configuration of the instancer while it's not in the scene tree. Whether that's supposed to happen or not is subject to the same need for reproduction steps. I dont think it's related to your issue though.

**Comment by DeepCanionStudio** [comment]
i copied the project where the bug happens and reduced it to the bare essentials
https://github.com/DeepCanionStudio/Voxel-Tools-Instancing-Glitch

**Comment by Zylann** [comment]
The link doesn't work

**Comment by DeepCanionStudio** [comment]
i forgot to make it public, fixed now

**Comment by Zylann** [comment]
I suppose I have to launch `solar_system.tscn`?
There are a lot of errors:

And when it's finished loading I'm here:
![image](https://github.com/Zylann/godot_voxel/assets/1311555/484d11f7-0756-475a-a5fb-67aed1fb79c7)
And I can't do anything but look around with a weird-angled camera.

**Comment by DeepCanionStudio** [comment]
i forgot to change this when i committed the project, the planet needs to be at x = 3700

**Comment by DeepCanionStudio** [comment]
> And when it's finished loading I'm here:
i forgot to change this when i committed the project, the planet needs to be at x = 3700




> Unless you have a quick fix to that, you should really find a more minimal way of reproducing that issue, because there are way too many things going on.
i removed as much stuff as i could without having to make the project from scratch (i tried making it from scratch but the issue never appeard)

**Comment by Zylann** [comment]
Unfortunately that doesn't fix it: when I investigate projects like this, I run the engine in debug mode, which is significantly slower. Your game is not accounting for the possibility that the player could reach the ground before ground collision is generated, so I fall through the planet and end up very far away. But again, if the repro was better constrained than that it would be easier.

**Comment by DeepCanionStudio** [comment]
for some reason the planet is considered far from the ship when it's at 0 0 0 and theres a line in the code that deactivates the collision when the planet is far from the ship, that is why moving the planet should work, if the problem is the collision taking more time just move the player farther from the center

**Comment by Zylann** [comment]
I already tried turning off the character's physics process if the area isn't loaded, but it is... so I guess it's because of your other logic thing turning off collision? (which again is one of the *many* things that should be a non-issue if the project was properly constrained to work as a repro project).

> that is why moving the planet should work

I already moved the planet to x=3700. It changes stuff but it doesn't help getting anywhere close to a state where the bug can begin to be reproduced.

https://github.com/Zylann/godot_voxel/assets/1311555/71a2ab51-d016-401b-b982-b7a973494afd

**Comment by DeepCanionStudio** [comment]
i updated the repository and now there's nothing aside from the planet and the player that can move and modify the terrain

**Comment by Zylann** [comment]
Is the issue still happening for you if you turn off FSR2?

**Comment by DeepCanionStudio** [comment]
it's fixed, that was actually the problem, thanks,

**Comment by Zylann** [comment]
Well... no, it's not fixed, at least not in Godot. This shows there is apparently a bug in Godot that somehow links FSR2 to multimeshes randomly getting garbage. 

I tried turning off FSR2 at runtime after the issue started happening, but it didn't "fix" it. Though maybe the issue occurs at the time multimeshes get modified.

**Comment by DeepCanionStudio** [comment]
yea it's not fixed but at least there is the solution of not using FSR2, and FSR1 works so for now i think it's fine, 
although this problem should be mentioned in the documentation

**Comment by Zylann** [comment]
Bugs should not be "documented", they should be reported in the issue tracker. I could not find one linked about multimeshes and FSR2. 
Is the minimal project you made from scratch earlier able to reproduce the issue now, if you use FSR2 in it?
