### ISSUE TITLE
Instances behaves irregularly and not as intended when using VoxelTool to edit the terrain

### ISSUE THREAD

**Issue by Critsium-xy** [Zylann/godot_voxel#719]
https://github.com/user-attachments/assets/6bb50ab5-1afc-4a86-92a5-321fe7c9c75a

When I use the VoxelTool to modify the terrain in game, I found that the instances on the surface behaves very strangely. Sometimes delete a small part of terrain will caues a huge area of instances disappear. Sometimes modify the terrain will not affect the instances at all. What's more, I find that every time I change a property of the instance generator, an error will occur.

![image](https://github.com/user-attachments/assets/36188f61-359a-4297-ac46-2a91fc569f08)

This is what my tree is like and the VoxelInstancer settings.

![image](https://github.com/user-attachments/assets/1c9af7d8-3ca0-479d-88d5-c6ded98d2827)
![image](https://github.com/user-attachments/assets/afe02711-4ff6-4581-8b8f-6c0fa1435550)

Is it my way of using the instancer is wrong? Or it's a bug or something else?
I used the newest build in the github's action part for windows.

**Comment by Zylann** [comment]
Can you provide a minimal test project?

**Comment by Janorico** [comment]
[``VoxelInstanceLibraryItem.persistent``](https://voxel-tools.readthedocs.io/en/latest/api/VoxelInstanceLibraryItem/#i_persistent) might help.

**Comment by Zylann** [comment]
`persistent` relates to saving edits. I don't think it will help with how the terrain detects which instances to remove during edition.

As for the error, it happens in the editor because for some reason VoxelInstancer cannot find its World3D, which makes no sense because any node inside the scene should have access to the world. Hence why I would need a minimal test project to understand what particular setup is causing that.

**Comment by Critsium-xy** [comment]
I finally found where the problem is. I tried to make a minimal project, but I find it difficult because this bug will never occur in another new project. I tried every different option between the two project and found that it is the TAA option that caused the bug. If you enabling TAA then this bug will happen. I don't know why but maybe no minimal project is needed for this?

**Comment by Zylann** [comment]
I don't understand how TAA has anything to do with this. Also, which of the two issues did you link TAA with?

**Comment by Critsium-xy** [comment]
The incorrect behavior of instancers. In regard to another problem, the problems are probably because I saved the VoxelLodTerrain node as a single file. When I edit the terrain and instances in the file, the root node is just the terrain, so maybe this is where these errors are from?

**Comment by Zylann** [comment]
I have a feeling this TAA issue is a Godot bug. When TAA is enabled, Godot allocates extra memory to store motion vectors (which is wasteful, because instancers are static and don't move so storing motion vectors for every blade of grass is just a giant waste). When you edit the ground, the instancer currently requests the list of instance positions from Godot, but maybe Godot doesn't return it correctly due to the extra data?

> When I edit the terrain and instances in the file, the root node is just the terrain, so maybe this is where these errors are from?

I'm not sure how that explains the errors printed.
My current suspicion is the following:
If you delete a VoxelInstancer, and then edit its library, you will get the error, because when you delete a node, *Godot does not actually delete it*. Instead it keeps it around in the UndoRedo history. So the VoxelInstancer is oblivious of what is happening and is still connected to its library, and therefore still listens to changes, and when you do a change it tries to update instances, which it can't do because it no longer has access to the world.

**Comment by Critsium-xy** [comment]
At least my problems are solved for now. Thanks a lot! This voxel extension is really useful for me. Maybe I will also do some part for this repo later.

**Comment by Zylann** [comment]
Well things are not solved though, more people will get issues with TAA until it gets identified and fixed

**Comment by Zylann** [comment]
You said you got the latest build from Github Actions, but which version of Godot are you seeing in the editor?

**Comment by Critsium-xy** [comment]
> You said you got the latest build from Github Actions, but which version of Godot are you seeing in the editor? If you see 4.3, then you experienced [godotengine/godot#93958](https://github.com/godotengine/godot/issues/93958), which will be fixed in 4.4.

Exactly 4.3. I'm happy it will soon be fixed.
