### ISSUE TITLE
Add configurable weight threshold for Voxel Texture Filter instancing

### ISSUE THREAD

**Issue by moongdevstudio** [Zylann/godot_voxel#774]
When using VoxelInstancer with material filtering (voxel_texture_filter), instances are spawned as soon as a material weight exceeds a hardcoded threshold of 128/255 (≈50%).

This causes unwanted spawning in transition zones where materials are blended. For example, grass props may spawn in areas that visually appear to be dirt, because there's still enough grass material weight in the blend, resulting in visual inconsistencies between terrain appearance and prop placement.

**Describe the solution you'd like:**
Add a configurable property to VoxelInstanceGenerator, such as:
material_weight_threshold: float = 0.5
This would control how "pure" a material needs to be before allowing instance spawning. Internally, this would replace the current hardcoded comparison:
const unsigned int weight_threshold = 128;

This would allow to:

Set higher thresholds (e.g. 0.8) to spawn only on nearly pure materials
Avoid instances appearing in visually blended zones
Match visual terrain blending with prop placement more accurately

A global setting for the whole instancer could work out too but having it in the generator would be better.

🛠️ Alternatives I've tried
Noise filters: Used to exclude transition zones — imprecise and requires extra setup
Manual safety margins in material generation: Pushes the responsibility to the wrong layer
Tuning blend weights to remain below 50%: Hacky, and may reduce visual fidelity

Example use cases:
Grass only spawns on 90%+ grass material
Rocks only appear on 80%+ pure rock surfaces
Trees avoid semi-grass/semi-rock terrain

Screenshot showing the issue with grass (sometimes it's worse than this)
<img width="724" height="358" alt="Image" src="https://github.com/user-attachments/assets/662cb688-1428-4386-be68-66653e46b6ae" />

**Comment by moongdevstudio** [comment]
> You can give a try with [8a4c288](https://github.com/Zylann/godot_voxel/commit/8a4c28819f86536b26e87f6b2ceb34afbc0777fd)

<img width="670" height="35" alt="Image" src="https://github.com/user-attachments/assets/31e36297-7003-439c-bac8-986d38345b8e" />

Thanks. I'm getting this in the editor.

**Comment by Zylann** [comment]
Fixed 922dac31074304f3a91fb3e9b226892512b5c257

**Comment by moongdevstudio** [comment]
> Fixed [922dac3](https://github.com/Zylann/godot_voxel/commit/922dac31074304f3a91fb3e9b226892512b5c257)

Still getting an issue I can't set it to anything it always resets to 0

I think this is because of this line 
const float threshold = math::clamp(p_threshold, 0.f, 0.f);

which should be
const float threshold = math::clamp(p_threshold, 0.f, 1.f);

**Comment by moongdevstudio** [comment]
Seem to work now! but not completely I think

This is with threshold at 0.90

<img width="1192" height="655" alt="Image" src="https://github.com/user-attachments/assets/39af839f-587b-4a62-8668-2c97014039d4" />

Same exact angle with threshold at 0.10
<img width="1226" height="675" alt="Image" src="https://github.com/user-attachments/assets/c00b0d8e-4d30-469f-a5ec-3d0001d5e133" />

You can see that the variable is working but still for some reason I can't set it to anything above 0.94 (no spawn at all)

I should logically be able to set it to 1.00 for full-texture only.

And a third screenshot showing some case where I think it shouldn't spawn but still does

<img width="857" height="558" alt="Image" src="https://github.com/user-attachments/assets/65f3f5f1-378f-4ccd-9c6c-baf4288e28b0" />

There is barely any grass yes it passes as higher than 0.4 in the middle part

This one might be linked to how I generate my terrain

**Comment by Zylann** [comment]
This is going to depend on how you set things up... 
Also the way filtering is done currently is by finding if any of the vertices of the triangle has a threshold higher than the threshold, it's not interpolating. Doing interpolation requires more work.
Also if nothing spawns above 0.94 that could be because weights arent perfectly normalized, due to the fact they are generated from extremely low-resolution data (with Mixel4, voxel weights are only 4bits, and with Single they are binary). Which would mean they have to be normalized here too, which is also extra work.

**Comment by Zylann** [comment]
I found a way to improve it 7f5be9cc5c9afbf8b8e7e7b6b42c98cbbccb72f6

**Comment by moongdevstudio** [comment]
> I found a way to improve it [7f5be9c](https://github.com/Zylann/godot_voxel/commit/7f5be9cc5c9afbf8b8e7e7b6b42c98cbbccb72f6) It's undeniably slower of course, but along the way I found a better algorithm to spread instances on triangles.

<img width="1229" height="526" alt="Image" src="https://github.com/user-attachments/assets/a866e988-024e-4729-9520-2b1c7cb1298f" />

<img width="840" height="595" alt="Image" src="https://github.com/user-attachments/assets/e8a66c69-4f47-44a7-aedf-e03fb0029194" />

Just tried it looks perfect when setting it at 1.0 now and without any extra work on the generation! 

Thank you so much for this
